### ISSUE TITLE
cant see it in the community repo

### ISSUE THREAD

**Issue by zeltak** [rusi/obsidian-colorful-note-borders#1]
Hi, this plugin is epic!

just a heads up for me it still does not appear in the third-party plugins in obsidian 

thx so much for your great work!

Z

**Comment by JimKnecht** [comment]
It doesn't show up for me either. Colorful Tag does but not borders.

**Comment by nima** [comment]
Same experience here.

**Comment by rusi** [comment]
it took a bit for the plugin to be accepted, but it is now in the community repo
