### ISSUE TITLE
No bottom border on iPhone (with the keyboard hidden).

### ISSUE THREAD

**Issue by lebigot** [rusi/obsidian-colorful-note-borders#13]
On iPhone (13 Pro), when displaying a note without the keyboard shown, the bottom of the note has no border (maybe it's hidden by the tool (?) ribbon at the bottom of the screen?).

I'm not sure if this is a bug with this plugin or with Obsidian (which could explain why sometimes we don't see the search result of obsidian, which may be hidden below the bottom of the displayed note)…

Thanks!

**Comment by rusi** [comment]
yes, I think the border is hidden by the toolbar and I don't know how to fix that on mobile...
