### ISSUE TITLE
FR: Border width

### ISSUE THREAD

**Issue by TfTHacker** [rusi/obsidian-colorful-note-borders#9]
I am sure this is configurable with CSS, but it would also be nice to define the border width in the UI. In many cases, I could see it useful to have a thin border, just as an accent. However, sometimes it might be helpful to have a thicker border.

**Comment by demian0311** [comment]
Same, I'm not a front-end guy but I'm having trouble finding the CSS class to tweak the border style.  I really like the plugin but I'd like something a bit more subtle, maybe aligning to just the left or top border.

**Comment by demian0311** [comment]
The border width is hard-coded to 5px [here](https://github.com/rusi/obsidian-colorful-note-borders/blob/91f980ce90d037934d7961925c4a831f11108651/src/main.ts#L73).  It'd be cool if the width and style were configurable via the settings.

**Comment by rusi** [comment]
Duplicate of #2
